### ISSUE TITLE
[小改良  Little modification] - Gripper Microswitch

### ISSUE THREAD

**Issue by jpliew** [206cc/PicoBETH#5]
非常感谢你的分享。珠夹方面我做了个小改良，拉线时可以直接触碰开关。

如果有时间请试试看是否适合？

小型微开关是从淘宝买的
https://item.taobao.com/item.htm?_u=r11e7bloc841&id=568953039456&skuId=4840196680776&spm=a1z09.2.0.0.4ce82e8dkcG8wB

![image](https://github.com/user-attachments/assets/89ed15a0-2c18-4a79-aeb4-a8e4597e2dbd)

![image](https://github.com/user-attachments/assets/53f6d52d-ea5b-4d1e-9892-d6d252c085bc)

![image](https://github.com/user-attachments/assets/614bd2ec-c081-41d1-996e-8f8a9ec5f9ce)

[BadmintonTensionClampSwitch.zip](https://github.com/user-attachments/files/17158580/BadmintonTensionClampSwitch.zip)

附上3D档案。

再次谢谢你的分享。

**Comment by 206cc** [comment]
看起來非常好，也很美觀，我會找時間試試。雖然我沒有3D列印機，但我會想辦法做一個類似的固定架。感謝您的貢獻!

**Comment by 206cc** [comment]
https://github.com/user-attachments/assets/ad17be02-75dd-407b-8556-c48591de04bc

我剛剛嘗試安裝，成果非常美觀且滑順，移植過程中需要注意兩個事項：

1. 微動開關需接 NC（原本是 NO）。
2. 程式碼有一處需修改，如下所示：

在 `def start_tensioning():` 中找到：

```
if button_head_pressed or button_exit_pressed or rt_mode_pressed:
```

需在 button_head_pressed 前加上 not，修改為：

```
if not button_head_pressed or button_exit_pressed or rt_mode_pressed:
```

這表示反向按鍵偵測（如果不修改此行，緊到磅後會立即退回）。

修改後會出現一個小問題：當按下珠夾頭上的按鍵退回時，因為按鍵偵測是非阻塞的，需等待最多 0.5 秒，在影片的第17秒處可以看到這一點，改按EXIT鍵離開會更快。除此之外，目前尚未發現其他問題。我會在測試幾隻球拍之後，確認沒問題後，開一個專門介紹這個改良珠夾開關的分支，並說明這是您的點子，非常感謝您的貢獻！

**Comment by DeeeFoo** [comment]
Hi, I 3D-printed the bracket, but my micro switch is too big to fit into it. Did you use a different size of micro switch?

**Comment by jpliew** [comment]
@DeeeFoo , I bought the microswitch from Taobao. 

https://item.taobao.com/item.htm?id=568953039456

<img width="750" height="753" alt="Image" src="https://github.com/user-attachments/assets/f5a8b032-3ebc-40fc-a218-2490bfb8c175" />

If you live in the Western world, you can try AliExpress. However, the measurements seem a bit off. I’m not sure whether the seller measured them incorrectly or made a typo. If you’ve already purchased this and the dimensions don’t quite match, you can edit the 3D file. If you’re unable to do so, just let me know the exact measurements and I can help modify the 3D file for you.

https://www.aliexpress.com/item/1005008715678557.html

Hope this helps.

Cheers.

**Comment by DeeeFoo** [comment]
The ones I bought are identical to the one below. These are pretty standard microswitches, so I thought the dimensions were universal. It shows the exact measurements on the product page. 

https://www.amazon.com/HiLetgo-KW12-3-Roller-Switch-Normally/dp/B07X142VGC?crid=1DXGX6TSJBL0J&dib=eyJ2IjoiMSJ9.pA5AhTLsuZxbQ596uoA9nIkAG3zC5zc6VuueUWSxTPLvkxGutE4XW3QiJBwF356RcS_UmyQpWCtqTHqJW1mtfe5OTBUXTxFTALqVZyW31VD-CwzKO7GpJ3pL1KYnLVU7H0uWIMFplDl3oSeh634Weopz1s7ULENxGGi508PW7ep_DF8QUbAX9bn2yAAf0uQQSl9l1icyBwyBb0nKDkRiybahq8ORZwmliP9oYruRQHQ.gh8LdHd_kY4CHu87BtWwfP2FszGs-h9rdJXKX5WB9cM&dib_tag=se&keywords=micro+switch&qid=1769643143&sprefix=micro+switc%2Caps%2C183&sr=8-1

Seems like the size is a little bit different from the one you have. I do not know how to edit 3D models, would greatly appreciate it if you could edit it. No rush, whenever works for you.

Thanks!

**Comment by jpliew** [comment]
@DeeeFoo , I tried to model the switch without having the real switch. There might be some tolerances that you may need to adjust with files or drill.

<img width="964" height="677" alt="Image" src="https://github.com/user-attachments/assets/e25172ab-b07b-4989-9e97-f0be02ccd4e4" />

<img width="840" height="678" alt="Image" src="https://github.com/user-attachments/assets/79f61316-e0ff-4727-8151-809389dce09f" />


[BadmintonTensionHeadSwitch KW12.zip](https://github.com/user-attachments/files/25008123/BadmintonTensionHeadSwitch.KW12.zip)

Hope this helps.

Cheers

**Comment by 206cc** [comment]
Thanks jpliew for sharing this improved clamp-head start switch — it’s super convenient for badminton stringing. I’ll update the 3D-print file on the project branch page so others can use it too.
